name: Performance Test

on:
  pull_request:
    branches:
      - main
      - develop
jobs:
  lighthouseci:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Corepack
        run: npm install -g corepack

      - name: Active Corepack
        run: corepack enable

      - run: yarn set version stable

      - name: Install Dependencies
        run: yarn install
      # yarn add @lhci/cli@0.12.x

      - name: Build Application
        run: yarn build

      - name: Run Lighthouse CI
        run: yarn lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

      - name: Slack Notification on Failure
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        if: ${{ failure() }}
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "デプロイ失敗しました😢\n result: ${{ job.status }}\n lint-check Action: ${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
