name: Performance Test

on: [push]
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Corepack
        run: npm install -g corepack

      - name: Active Corepack
        run: corepack enable

      - name: Install Dependencies
        run: |
          yarn set version stable
          yarn install --immutable --immutable-cache
        # yarn add @lhci/cli@0.12.x

      - name: Build Application
        run: yarn build

      - name: Run Lighthouse CI
        run: lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
