name: Performance Test

on: [push]
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Corepack
        run: npm install -g corepack

      - name: Active Corepack
        run: corepack enable

      - run: yarn set version stable

      - name: Install Dependencies
        run: yarn install --immutable --immutable-cache
      # yarn add @lhci/cli@0.12.x

      - name: Build Application
        run: yarn build

      - name: Run Lighthouse CI
        run: yarn lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
