name: Storybook Tests
on:
  pull_request:
    branches:
      - main
      - develop
jobs:
  storybook:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node.js and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Corepack
        run: npm install -g corepack
      - name: Active Corepack
        run: corepack enable
      - run: yarn set version stable

      - name: Install Dependencies
        run: yarn install

      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Build Storybook
        run: yarn build-storybook --quiet
      - name: Serve Storybook and run tests
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx http-server storybook-static --port 6006 --silent" \
            "npx wait-on tcp:127.0.0.1:6006 && yarn test-storybook"
